from pathlib import Path

from .io import read_json
from .manifest import load_manifest, save_manifest, update_stage


def evidence_suffix(item: dict) -> str:
    refs = item.get("evidence", [])
    if not refs:
        return ""
    rendered = []
    for ref in refs:
        page = "?" if ref.get("page_index") is None else ref["page_index"] + 1
        rendered.append(f"`{ref['document_id']}:{ref['block_id']}:p{page}`")
    return " " + " ".join(rendered)


def render_statements(items: list[dict], empty: str = "Not extracted.") -> list[str]:
    if not items:
        return [empty]
    return [f"- {item['statement']}{evidence_suffix(item)}" for item in items]


def corpus_records(corpus: Path):
    for record_dir in sorted((corpus / "records").glob("work_*")):
        work = read_json(record_dir / "work.json", {})
        analysis = read_json(record_dir / "analysis.json", {})
        experiments = read_json(record_dir / "experiments.json", {})
        taxonomy = read_json(record_dir / "taxonomy.json", {})
        if work:
            yield work, analysis, experiments, taxonomy


def write_methodology(corpus: Path, records: list[tuple]) -> None:
    lines = ["# Corpus Methodology Analysis", "", "Evidence references use `document:block:page`.", ""]
    for work, analysis, _, taxonomy in records:
        lines.extend([f"## {work['title']}", "", "### Research problem", ""])
        lines.extend(render_statements(analysis.get("research_problem", [])))
        lines.extend(["", "### Methodology", ""])
        lines.extend(render_statements(analysis.get("methodology", [])))
        methods = taxonomy.get("facets", {}).get("method_family", [])
        if methods:
            lines.extend(["", "### Method families", ""])
            lines.extend(f"- {item['name']}" for item in methods)
        lines.append("")
    (corpus / "synthesis" / "methodology.md").write_text("\n".join(lines), encoding="utf-8")


def write_experiments(corpus: Path, records: list[tuple]) -> None:
    lines = ["# Corpus Experiment and Result Analysis", ""]
    for work, _, experiments, _ in records:
        lines.extend([f"## {work['title']}", "", "### Datasets", ""])
        datasets = experiments.get("datasets", [])
        lines.extend([f"- {item['name']}{evidence_suffix(item)}" for item in datasets] or ["Not extracted."])
        lines.extend(["", "### Metrics", ""])
        metrics = experiments.get("metrics", [])
        lines.extend([f"- {item['name']}{evidence_suffix(item)}" for item in metrics] or ["Not extracted."])
        lines.extend(["", "### Experimental details", ""])
        lines.extend(render_statements(experiments.get("implementation_details", [])))
        lines.extend(["", "### Reported numerical results", ""])
        lines.extend(render_statements(experiments.get("results", [])))
        lines.append("")
    (corpus / "synthesis" / "experiments.md").write_text("\n".join(lines), encoding="utf-8")


def write_datasets(corpus: Path, records: list[tuple]) -> None:
    usage = {}
    for work, _, experiments, taxonomy in records:
        for dataset in experiments.get("datasets", []):
            usage.setdefault(dataset["name"], []).append((work, dataset))
        for dataset in taxonomy.get("facets", {}).get("dataset", []):
            usage.setdefault(dataset["name"], []).append((work, dataset))
    lines = ["# Corpus Dataset Index", ""]
    if not usage:
        lines.append("No datasets were deterministically identified.")
    for name, uses in sorted(usage.items()):
        lines.extend([f"## {name}", ""])
        for work, dataset in uses:
            lines.append(f"- **{work['title']}**{evidence_suffix(dataset)}")
        lines.append("")
    (corpus / "synthesis" / "datasets.md").write_text("\n".join(lines), encoding="utf-8")


def write_review(corpus: Path, records: list[tuple]) -> None:
    facets = {}
    for work, _, _, taxonomy in records:
        for facet, assignments in taxonomy.get("facets", {}).items():
            for assignment in assignments:
                facets.setdefault((facet, assignment["name"]), []).append(work["title"])
    lines = [
        "# Evidence-Backed Literature Review Index", "",
        "This is a deterministic thematic index, not a model-authored narrative. Claims should be checked through the cited methodology and experiment reports.", "",
        "## Corpus scope", "", f"The corpus contains {len(records)} normalized scholarly works.", "",
    ]
    for (facet, label), titles in sorted(facets.items()):
        lines.extend([f"## {facet.replace('_', ' ').title()}: {label}", ""])
        lines.extend(f"- {title}" for title in sorted(titles))
        lines.append("")
    lines.extend([
        "## Research gaps", "",
        "Gap claims are intentionally not generated by the deterministic pipeline. They require cross-paper interpretation and manual evidence review or a configured semantic model.", "",
    ])
    (corpus / "synthesis" / "literature_review.md").write_text("\n".join(lines), encoding="utf-8")


def write_all_papers(corpus: Path, records: list[tuple]) -> None:
    lines = ["# Complete Normalized Corpus", ""]
    for work, _, _, _ in records:
        for document_id in work["document_ids"]:
            paper_path = corpus / "papers" / document_id / "paper.md"
            lines.extend(["---", "", f"# {work['title']}", "", f"Document ID: `{document_id}`", ""])
            if paper_path.exists():
                markdown = paper_path.read_text(encoding="utf-8", errors="ignore")
                asset_prefix = f"../papers/{document_id}/assets/"
                markdown = markdown.replace("](assets/", f"]({asset_prefix}")
                markdown = markdown.replace('src="assets/', f'src="{asset_prefix}')
                lines.append(markdown)
            lines.append("")
    (corpus / "synthesis" / "all_papers.md").write_text("\n".join(lines), encoding="utf-8")


def synthesize_corpus(corpus: Path) -> dict[str, int]:
    output_dir = corpus / "synthesis"
    output_dir.mkdir(parents=True, exist_ok=True)
    records = list(corpus_records(corpus))
    write_methodology(corpus, records)
    write_experiments(corpus, records)
    write_datasets(corpus, records)
    write_review(corpus, records)
    write_all_papers(corpus, records)
    manifest = load_manifest(corpus)
    included = {document_id for work, _, _, _ in records for document_id in work["document_ids"]}
    for record in manifest:
        if record["document_id"] in included:
            update_stage(record, "synthesis", "included")
    if manifest:
        save_manifest(corpus, manifest)
    return {"works": len(records), "reports": 5}
